update alpine image | added debian image
vathes/k8s-admin-docker pull request #15
Opened 2022-05-17 15:52 UTC by yambottle

2022-05-17 17:06 UTC, Ernaldis approved these changes

2022-08-29 20:44 UTC, guzman-raphael requested changes
Thanks @yambottle! Have a few remaining questions for this one.

2022-08-29 20:44 UTC, guzman-raphael commented on dist/alpine/Dockerfile
> +	apk add --no-cache bash curl jq openssh openssl util-linux bind-tools && \
I see bind-tools useful for using `dig` in debugging DNS. What's specifically useful for debugging from `util-linux`?

2022-08-29 20:44 UTC, guzman-raphael commented on dist/alpine/Dockerfile
> +	set -x; > /etc/inittab && mkdir /main && \
`set -x` can be useful to display the actual command that is running. A bit unclear on what is the purpose for removing `/etc/inittab` though. :thinking:

2022-08-29 20:44 UTC, guzman-raphael commented on dist/alpine/docker-compose.yml
> +    image: registry.vathes.com/vathes/k8s-admin:kops${KOPS_VERSION}-helm${HELM_VERSION}-alpine
Since this image is public we published it to Docker Hub. We technically could get away with free storage on this one. :sweat_smile:

2022-08-29 20:44 UTC, guzman-raphael commented on dist/alpine/docker-compose.yml
> +        echo "$$0 running..."; echo "PATH: '$$PATH'"; tail -f /dev/null;
```suggestion
      - |       
        echo "$$0 running..."
        echo "PATH: '$$PATH'"
        tail -f /dev/null
```

2022-08-29 20:44 UTC, guzman-raphael commented on dist/debian/docker-compose.yml
> +      dockerfile: ./dist/alpine/Dockerfile
```suggestion
      dockerfile: ./dist/debian/Dockerfile
```

2022-08-29 20:44 UTC, guzman-raphael commented on dist/debian/docker-compose.yml
> +        echo "$$0 running..."; echo "PATH: '$$PATH'"; tail -f /dev/null;
```suggestion
    image: vathes/k8s-admin:kops${KOPS_VERSION}-helm${HELM_VERSION}-debian
    command:
      - bash
      - -c
      - |
        echo "$$0 running..."
        echo "PATH: '$$PATH'"
        tail -f /dev/null
```

2025-03-14 05:58 UTC, closed without merging